ALTER TABLE `contest`
	ADD COLUMN `disabled` BIT NOT NULL DEFAULT b'0' COMMENT 'disabled表示该比赛是否被禁用';
ALTER TABLE `mail`
	ADD COLUMN `disabled` BIT NOT NULL DEFAULT b'0';
ALTER TABLE `message`
	ADD COLUMN `disabled` BIT NOT NULL DEFAULT b'0';
ALTER TABLE `news`
	ADD COLUMN `disabled` BIT NOT NULL DEFAULT b'0';
ALTER TABLE `privilege`
	ADD COLUMN `disabled` BIT NOT NULL DEFAULT b'0';
ALTER TABLE `problem`
	ADD COLUMN `disabled` BIT NOT NULL DEFAULT b'0';
ALTER TABLE `users`
	ADD COLUMN `disabled` BIT NOT NULL DEFAULT b'0';
