update contest set disabled=IF(defunct!='N',1,0);
alter table contest drop column defunct;
update mail set disabled=IF(defunct!='N',1,0);
alter table mail drop column defunct;
update message set disabled=IF(defunct!='N',1,0);
alter table message drop column defunct;
update news set disabled=IF(defunct!='N',1,0);
alter table news drop column defunct;
update privilege set disabled=IF(defunct!='N',1,0);
alter table privilege drop column defunct;
update problem set disabled=IF(defunct!='N',1,0);
alter table problem drop column defunct;
update users set disabled=IF(defunct!='N',1,0);
alter table users drop column defunct;
