ALTER TABLE `contest`
	ADD COLUMN `created_time` DATETIME NULL DEFAULT NULL AFTER `disabled`,
	ADD COLUMN `modified_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `created_time`;
ALTER TABLE `language`
	ADD COLUMN `created_time` DATETIME NULL DEFAULT NULL AFTER `disabled`,
	ADD COLUMN `modified_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `created_time`;
ALTER TABLE `problem`
	ADD COLUMN `created_time` DATETIME NULL DEFAULT NULL AFTER `disabled`,
	ADD COLUMN `modified_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `created_time`;
ALTER TABLE `problem_i18n`
	ADD COLUMN `created_time` DATETIME NULL DEFAULT NULL AFTER `source`,
	ADD COLUMN `modified_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `created_time`;
ALTER TABLE `users`
	ADD COLUMN `created_time` DATETIME NULL DEFAULT NULL AFTER `disabled`,
	ADD COLUMN `modified_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `created_time`;
ALTER TABLE `contest`
	CHANGE COLUMN `created_time` `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `disabled`,
	CHANGE COLUMN `modified_time` `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_time`;
ALTER TABLE `language`
	CHANGE COLUMN `created_time` `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `disabled`,
	CHANGE COLUMN `modified_time` `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_time`;
ALTER TABLE `problem`
	CHANGE COLUMN `created_time` `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `disabled`,
	CHANGE COLUMN `modified_time` `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `created_time`;
ALTER TABLE `problem_i18n`
	CHANGE COLUMN `created_time` `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `source`,
	CHANGE COLUMN `modified_time` `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_time`;
ALTER TABLE `users`
	CHANGE COLUMN `created_time` `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `disabled`,
	CHANGE COLUMN `modified_time` `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `created_time`;
