name: build

on: push

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java-version:
          - 8
          - 11
    name: test with jdk ${{ matrix.java-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start MariaDB
        uses: ankane/setup-mariadb@v1
        with:
          mariadb-version: 10.5
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}
      - uses: actions/cache@v2
        env:
          cache-name: maven-dependencies
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ github.workflow }}-${{ hashFiles('.github/**', '**/pom.xml') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ github.workflow }}-
            ${{ env.cache-name }}-
      - name: mvn verify
        run: ./mvnw -B --color=always -Dspring.datasource.password= verify
      - name: show dependency updates
        run: ./mvnw -B --color=always -U -Dmaven.version.rules=https://github.com/zhanhb/maven-shared/raw/main/version-rules.xml org.codehaus.mojo:versions-maven-plugin:display-property-updates org.codehaus.mojo:versions-maven-plugin:display-dependency-updates org.codehaus.mojo:versions-maven-plugin:display-plugin-updates
      - name: Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
      - name: Before Cache
        run: |
          ./mvnw -B --color=always build-helper:remove-project-artifact || :
          find ~/.m2/ -type d -name '*-SNAPSHOT' \( -exec rm -rf '{}' \; -prune \)
